site_name: LabyMod4 API

nav:
  - Addon API:
    - Introduction: pages/addon/index.md
    - Setup:
      - First Steps: pages/addon/setup/first-steps.md
      - Your first LabyMod 4 Addon: pages/addon/setup/setup.md
    - Features:
      - Creating a Configuration: pages/addon/features/config.md
      

plugins:
  - search

theme:
  name: material
  favicon: 'assets/theme/images/favicon.ico'
  logo: 'assets/theme/images/wolf.png'
  palette:
    scheme: slate
  feature:
    tabs: true
  features:
    - navigation.tabs
    - navigation.expand

extra_javascript: ['assets/theme/js/script.js']
extra_css: ['assets/theme/css/main.css']